export const GET_USERS = 'GET_USERS';
export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const INCREMENT_CORRECT_COUNT = 'INCREMENT_CORRECT_COUNT';
export const INCREMENT_INCORRECT_COUNT = 'DECREMENT_CORRECT_COUNT';
