const Types = {
  SET_CHARACTERS: 'SET_CHARACTERS',
  SET_MAIN_CHARACTER: 'SET_MAIN_CHARACTER',
  INCREMENT_CORRECT: 'INCREMENT_CORRECT',
  INCREMENT_INCORRECT: 'INCREMENT_INCORRECT'
};

export default Types;
